### ISSUE TITLE
So what do you recommend for CentOS as storage?

### ISSUE THREAD

**Issue by deitch** [jpetazzo/jpetazzo.github.io#7]
I would have commented on the post... but there is no commenting, so structured as an issue.

You seem to have dug pretty deeply into the issues with devicemapper and how to manage them. And there are definite performance questions. But given that some environments must run in CentOS, and the storage there is devicemapper, and it has the storage issues, what *do* you recommend for storage usage there? Both dev/build (where you are constantly setting up and tearing down containers) and production?

**Comment by jpetazzo** [comment]
I'd say: if you're running RHEL, follow the insturctions of your Red Hat support team (that's the whole point of paying for a RHEL subscription, I guess ;-))

If you're on CentOS, and without support, I'd look at BTRFS and make sure you use `filesys balance` regularly.

**Comment by deitch** [comment]
Are the devmapper issues resolved in CentOS/RHEL 7.x? It looked like it in my tests, but....

I don't mind btrfs, but try moving an ops team that in any case is struggling to absorb significant change. :-)

**Comment by jpetazzo** [comment]
Devmapper issues have been greatly improved with the release of the dynamic binaries; but I haven't played with it in a while, to be honest with you; so I'm just reporting second-hand information :)

**Comment by deitch** [comment]
And I am far from the expert!

My tests on CentOS 7 showed the size shrinking again proportionately when containers and images are removed. I didn't do anything too extensive, though.

I guess we will run with devmapper in CentOS 7 and a direct mount instead of loopback. We will just keep an eye on it. We will hope it lasts long enough to hold us until overlayfs makes it.

Thanks for the input. Closing the issue.
